/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOnlineOnlyRouteImport } from './routes/_authenticated/_online-only'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedNotesNewRouteImport } from './routes/_authenticated/notes/new'
import { Route as AuthenticatedOnlineOnlyTrashRouteImport } from './routes/_authenticated/_online-only/trash'
import { Route as AuthenticatedOnlineOnlyAuditLogRouteImport } from './routes/_authenticated/_online-only/audit-log'
import { Route as AuthenticatedOnlineOnlyAdminRouteImport } from './routes/_authenticated/_online-only/admin'
import { Route as AuthenticatedNotesNoteIdEditRouteImport } from './routes/_authenticated/notes/$noteId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnlineOnlyRoute = AuthenticatedOnlineOnlyRouteImport.update({
  id: '/_online-only',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedNotesNewRoute = AuthenticatedNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnlineOnlyTrashRoute =
  AuthenticatedOnlineOnlyTrashRouteImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => AuthenticatedOnlineOnlyRoute,
  } as any)
const AuthenticatedOnlineOnlyAuditLogRoute =
  AuthenticatedOnlineOnlyAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedOnlineOnlyRoute,
  } as any)
const AuthenticatedOnlineOnlyAdminRoute =
  AuthenticatedOnlineOnlyAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedOnlineOnlyRoute,
  } as any)
const AuthenticatedNotesNoteIdEditRoute =
  AuthenticatedNotesNoteIdEditRouteImport.update({
    id: '/notes/$noteId/edit',
    path: '/notes/$noteId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/admin': typeof AuthenticatedOnlineOnlyAdminRoute
  '/audit-log': typeof AuthenticatedOnlineOnlyAuditLogRoute
  '/trash': typeof AuthenticatedOnlineOnlyTrashRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/notes/$noteId/edit': typeof AuthenticatedNotesNoteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/admin': typeof AuthenticatedOnlineOnlyAdminRoute
  '/audit-log': typeof AuthenticatedOnlineOnlyAuditLogRoute
  '/trash': typeof AuthenticatedOnlineOnlyTrashRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/notes/$noteId/edit': typeof AuthenticatedNotesNoteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/_online-only': typeof AuthenticatedOnlineOnlyRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_online-only/admin': typeof AuthenticatedOnlineOnlyAdminRoute
  '/_authenticated/_online-only/audit-log': typeof AuthenticatedOnlineOnlyAuditLogRoute
  '/_authenticated/_online-only/trash': typeof AuthenticatedOnlineOnlyTrashRoute
  '/_authenticated/notes/new': typeof AuthenticatedNotesNewRoute
  '/_authenticated/notes/$noteId/edit': typeof AuthenticatedNotesNoteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/audit-log'
    | '/trash'
    | '/notes/new'
    | '/notes/$noteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/audit-log'
    | '/trash'
    | '/notes/new'
    | '/notes/$noteId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/_online-only'
    | '/_authenticated/'
    | '/_authenticated/_online-only/admin'
    | '/_authenticated/_online-only/audit-log'
    | '/_authenticated/_online-only/trash'
    | '/_authenticated/notes/new'
    | '/_authenticated/notes/$noteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_online-only': {
      id: '/_authenticated/_online-only'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnlineOnlyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/notes/new': {
      id: '/_authenticated/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AuthenticatedNotesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_online-only/trash': {
      id: '/_authenticated/_online-only/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedOnlineOnlyTrashRouteImport
      parentRoute: typeof AuthenticatedOnlineOnlyRoute
    }
    '/_authenticated/_online-only/audit-log': {
      id: '/_authenticated/_online-only/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedOnlineOnlyAuditLogRouteImport
      parentRoute: typeof AuthenticatedOnlineOnlyRoute
    }
    '/_authenticated/_online-only/admin': {
      id: '/_authenticated/_online-only/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedOnlineOnlyAdminRouteImport
      parentRoute: typeof AuthenticatedOnlineOnlyRoute
    }
    '/_authenticated/notes/$noteId/edit': {
      id: '/_authenticated/notes/$noteId/edit'
      path: '/notes/$noteId/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedOnlineOnlyRouteChildren {
  AuthenticatedOnlineOnlyAdminRoute: typeof AuthenticatedOnlineOnlyAdminRoute
  AuthenticatedOnlineOnlyAuditLogRoute: typeof AuthenticatedOnlineOnlyAuditLogRoute
  AuthenticatedOnlineOnlyTrashRoute: typeof AuthenticatedOnlineOnlyTrashRoute
}

const AuthenticatedOnlineOnlyRouteChildren: AuthenticatedOnlineOnlyRouteChildren =
  {
    AuthenticatedOnlineOnlyAdminRoute: AuthenticatedOnlineOnlyAdminRoute,
    AuthenticatedOnlineOnlyAuditLogRoute: AuthenticatedOnlineOnlyAuditLogRoute,
    AuthenticatedOnlineOnlyTrashRoute: AuthenticatedOnlineOnlyTrashRoute,
  }

const AuthenticatedOnlineOnlyRouteWithChildren =
  AuthenticatedOnlineOnlyRoute._addFileChildren(
    AuthenticatedOnlineOnlyRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOnlineOnlyRoute: typeof AuthenticatedOnlineOnlyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedNotesNewRoute: typeof AuthenticatedNotesNewRoute
  AuthenticatedNotesNoteIdEditRoute: typeof AuthenticatedNotesNoteIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnlineOnlyRoute: AuthenticatedOnlineOnlyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNotesNewRoute: AuthenticatedNotesNewRoute,
  AuthenticatedNotesNoteIdEditRoute: AuthenticatedNotesNoteIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
